---
- name: Install nginx and trivia
  yum:
    name: nginx
    state: latest
    update_cache: yes

- name: Make sure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Change nginx.conf file
  copy: dest=/etc/nginx/nginx.conf src=nginx_centos.conf owner=root group=root
  notify: restart nginx

- name: Add nginx conf.d configs
  copy: dest=/etc/nginx/conf.d/{{ item }}.conf src=conf.d/{{ item }}.conf owner=root group=root
  loop:
    - 00-conn
    - 01-gzip
    - 02-proxy
    - 03-timeout
    - 04-ssl
    - 05-open_file
  notify: restart nginx

- name: Create /etc/nginx/vhosts/
  file: state=directory path=/etc/nginx/vhosts/ mode=0755

- name: Add nginx vhosts configs
  template:
    src: "{{ item.file }}"
    dest: "{{ item.target }}"
    mode: 0644
  loop:
    - { file: 'vhost_centos.conf.j2', target: '/etc/nginx/vhosts/{{ vhost }}.conf' }
    - { file: 'ipvhost.conf.j2', target: '/etc/nginx/vhosts/{{ ansible_default_ipv4.address }}.conf' }
  notify: restart nginx

- name: fix nginx not starting with ipv6
  lineinfile:
    insertafter: '^\[Service\]'
    path: /etc/systemd/system/multi-user.target.wants/nginx.service
    line: 'ExecStartPre=/bin/sleep 10'

- name: Enable http(s) on firewall-cmd
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: public
  loop:
    - http
    - https

#TODO
# revise error in conf.d/04-ssl.conf
# nginx: [emerg] BIO_new_file("/etc/nginx/dhparam.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/dhparam.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
