---
- name: add remi repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install php-fpm
  yum:
    name: php-fpm
    enablerepo: remi-php72
    update_cache: yes
    state: latest

- name: ensure fpm is started and enabled
  service:
    name: "php-fpm"
    state: started

- name: install php modules
  yum:
    name: "{{ php_modules }}"
    state: latest
    enablerepo: remi-php72
  notify: reload centos php-fpm

- name: clear default pool file
  copy:
    content: '; disabled, use separate vhost pools'
    dest: /etc/php-fpm.d/www.conf
  notify: reload centos php-fpm

- name: create pool for a virtual host
  template:
    dest: /etc/php-fpm.d/{{ vhost }}.conf
    src: vhost_pool_centos.j2
  notify: reload centos php-fpm

- name: add cgi.fix_pathinfo = 0 to php.ini
  ini_file:
    path: /etc/php.ini
    section: PHP
    option: cgi.fix_pathinfo
    value: 0

- name: Create /var/www/ vhost subdir
  file:
    state: directory
    path: /var/www/{{ vhost }}/
    owner: apache
    group: apache
    mode: 0755

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    mode: 0644

- name: add fpm handler block for nginx
  blockinfile:
    path: /etc/nginx/vhosts/{{ vhost }}.conf
    insertafter: '^## handler'
    block: |
      location ~ \.php$ {
              fastcgi_index index.php;
              fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f webmaster@{{ vhost }}";
              fastcgi_pass unix:/var/run/php-fpm/{{ vhost }}.sock;
              fastcgi_split_path_info ^((?U).+\.ph(?:p\d*|tml))(/?.+)$;
              try_files $uri =404;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;

              fastcgi_read_timeout 300;
              fastcgi_busy_buffers_size 16k;
              fastcgi_buffers 32 16k;
      }
  notify: restart nginx
