---
- name: add remi repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install php-fpm
  yum:
    name: php-fpm
    enablerepo: remi-php72
    update_cache: yes
    state: latest

- name: ensure fpm is started and enabled
  service:
    name: "php-fpm"
    state: started

- name: install php modules
  yum:
    name: "{{ php_modules }}"
    state: latest
    enablerepo: remi-php72
  notify: reload centos php-fpm

- name: clear default pool file
  copy:
    content: '; disabled, use separate vhost pools'
    dest: /etc/php-fpm.d/www.conf
  notify: reload centos php-fpm

- name: create pool for a virtual host
  template:
    dest: /etc/php-fpm.d/{{ ansible_nodename }}.conf
    src: vhost_pool_centos.j2
  notify: reload centos php-fpm

- name: add cgi.fix_pathinfo = 0 to php.ini
  ini_file:
    path: /etc/php.ini
    section: PHP
    option: cgi.fix_pathinfo
    value: 0

  #lineinfile:
  #  path: /etc/php.ini
  #  regex: '^cgi.fix_pathinfo'
  #  line: '^cgi.fix_pathinfo = 0'

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ ansible_nodename }}/index.php
    mode: 0644
