---
- name: add ppa:ondrej/php
  apt_repository:
    update_cache: yes
    repo: ppa:ondrej/php

- name: install fpm for client chosen php-version
  apt:
    name: php{{ php_version_u }}-fpm
    update_cache: yes
    state: latest

- name: install fpm 7.2 for pma
  apt:
    name: php7.2-fpm
    state: latest

- name: install php modules for selected php version
  apt:
    name: php7.3-{{ php_modules_u }}
    state: latest
  notify: restart debian php-fpm
  when: php_version_u == '7.3'

- name: clear default pool file
  copy:
    content: '; disabled, use separate vhost pools'
    dest: /etc/php/{{ php_version_u }}/fpm/pool.d/www.conf
  notify: restart debian php-fpm

- name: create pool for a virtual host
  template:
    dest: /etc/php/{{ php_version_u }}/fpm/pool.d/{{ vhost }}.conf
    src: vhost_pool_debian.j2
  notify: restart debian php-fpm

- name: add cgi.fix_pathinfo = 0 to php.ini
  ini_file:
    path: /etc/php/{{ php_version_u }}/cli/php.ini
    section: PHP
    option: cgi.fix_pathinfo
    value: 0

- name: Create /var/www/ vhost subdir
  file:
    state: directory
    path: /var/www/{{ vhost }}/
    owner: www-data
    group: www-data
    mode: 0755

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    mode: 0644

- name: add fpm handler block for nginx
  blockinfile:
    path: /etc/nginx/vhosts/{{ vhost }}.conf
    insertafter: '^## handler'
    block: |
      location ~ \.php$ {
              fastcgi_index index.php;
              fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f webmaster@{{ vhost }}";
              fastcgi_pass unix:/var/run/php/{{ vhost }}.sock;
              fastcgi_split_path_info ^((?U).+\.ph(?:p\d*|tml))(/?.+)$;
              try_files $uri =404;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;

              fastcgi_read_timeout 300;
              fastcgi_busy_buffers_size 16k;
              fastcgi_buffers 32 16k;
      }
  notify: restart nginx

- name: ensure both fpms are started and enabled
  service:
    name: {{ item }}
    enabled: yes
    state: started
  loop:
    - php{{ php_version_u }}-fpm
    - php7.2-fpm
