---
- name: add ppa:ondrej/php
  apt_repository:
    update_cache: yes
    repo: ppa:ondrej/php

- name: install php-fpm
  apt:
    name: php{{ php_version }}-fpm
    update_cache: yes
    state: latest

- name: ensure fpm is started and enabled
  service:
    name: "php{{ php_version }}-fpm"
    state: started

- name: install php modules 7.3
  apt:
    name: php7.3-{{ php_modules_u }}
    state: latest
  notify: reload debian php-fpm
  when: php_version == '7.3'

- name: install php modules 5.6
  apt:
    name: php5.6-{{ php_modules_u }}
    state: latest
  notify: reload debian php-fpm
  when: php_version == '5.6'

- name: delete default pool file
  file:
    state: absent
    path: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
  notify: reload debian php-fpm

- name: create pool for a virtual host
  template:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/{{ ansible_nodename }}.conf
    src: vhost_pool_debian.j2
  notify: reload debian php-fpm

- name: add cgi.fix_pathinfo = 0 to php.ini
  ini_file:
    path: /etc/php/{{ php_version }}/cli/php.ini
    section: PHP
    option: cgi.fix_pathinfo
    value: 0

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ ansible_nodename }}/index.php
    mode: 0644
