---
- name: add remi repository
  yum:
    name: http://mirror.neolabs.kz/remi/enterprise/remi-release-7.rpm
    state: present

- name: install httpd
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: ensure httpd is enabled
  service:
    name: httpd
    enabled: yes

- name: install mod_php
  yum:
    name: php{{ php_version }}-php
    state: latest
    enablerepo: remi-php{{ php_version }}
  notify: restart httpd

- name: install php modules
  yum:
    #name: "{{ php_modules }}"
    name: php{{ php_version }}-{{ php_modules }}
    state: latest
    enablerepo: remi-php{{ php_version }}
  notify: restart httpd

- name: change listened port
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    line: 'Listen 127.0.0.1:8080'
  notify: restart httpd

- name: Create /var/www/ vhost subdir
  file:
    state: directory
    path: /var/www/{{ vhost }}/
    owner: apache
    group: apache
    mode: 0755

- name: add vhost config
  template:
    src: vhost_centos.j2
    dest: /etc/httpd/conf.d/{{ vhost }}.conf
  notify: restart httpd

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    owner: apache
    group: apache
    mode: 0644

- name: add php handler block for nginx
  blockinfile:
    path: /etc/nginx/vhosts/{{ vhost }}.conf
    insertafter: '^## handler'
    block: |
      location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 300;
        client_max_body_size 256m;

        proxy_buffer_size 16k;
        proxy_buffers 32 16k;
      }
  notify: restart nginx
