---
- name: install httpd
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: ensure httpd is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes

- name: delete default config file symlink
  copy:
    content: '; disabled, use separate vhost configs'
    dest: /etc/httpd/sites-enabled/000-default.conf
  notify: restart httpd

- name: add vhost config
  template:
    src: vhost_centos.j2
    dest: /etc/httpd/conf.d/{{ vhost }}.conf
  notify: restart httpd

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    mode: 0644

- name: add fpm handler block for nginx
  blockinfile:
    path: /etc/nginx/vhosts/{{ vhost }}.conf
    insertafter: '^## handler'
    block: |
      location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 300;
        client_max_body_size 256m;

        proxy_buffer_size 16k;
        proxy_buffers 32 16k;
      }
    notify: reload nginx
