---
- name: install apache2
  yum:
    name: apache2
    state: latest
    update_cache: yes

- name: ensure apache2 is enabled
  service:
    name: apache2
    enabled: yes

- name: clear default config file
  copy:
    content: '; disabled, use separate vhost configs'
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2

- name: add vhost config
  template:
    src: vhost.j2
    dest: /etc/apache2/sites-available/{{ vhost }}.conf
  notify: restart apache2

- name: create vhost file symlink
  file:
    state: link
    path: /etc/apache2/sites-enabled/{{ vhost }}.conf
    src: /etc/apache2/sites-available/{{ vhost }}.conf

- name: Create /var/www/ vhost subdir
  file:
    state: directory
    path: /var/www/{{ vhost }}/
    owner: www-data
    group: www-data
    mode: 0755

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    mode: 0644
