---
- name: install apache2
  yum:
    name: apache2
    state: latest
    update_cache: yes

- name: ensure apache2 is enabled
  service:
    name: apache2
    enabled: yes

- name: clear default config file
  copy:
    content: '# disabled, use separate vhost configs'
    dest: /etc/apache2/sites-enabled/000-default.conf
    follow: yes
  notify: restart apache2

- name: add vhost config
  template:
    src: vhost_debian.j2
    dest: /etc/apache2/sites-available/{{ vhost }}.conf
  notify: restart apache2

- name: create vhost file symlink
  file:
    state: link
    path: /etc/apache2/sites-enabled/{{ vhost }}.conf
    src: /etc/apache2/sites-available/{{ vhost }}.conf

- name: change listened port
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    line: 'Listen 127.0.0.1:8080'

- name: Create /var/www/ vhost subdir
  file:
    state: directory
    path: /var/www/{{ vhost }}/
    owner: www-data
    group: www-data
    mode: 0755

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    mode: 0644
