---
- name: Install apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Ensure apache2 is started and enabled
  service: name=apache2 state=started enabled=yes

- name: Delete default config file symlink
  copy:
    content: '; disabled, use separate vhost configs'
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2
