---
- name: restart php-fpm centos
  service:
    name: php-fpm
    state: restarted

- name: restart php-fpm debian
  service:
    name: php{{ php_version }}-fpm
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
