---
- name: install
  yum:
    name: "{{ main_packages }}"
    update_cache: yes
  vars:
    main_packages:
      - postfix
      - dovecot
      - dovecot-mysql

- name: create mailserver db
  mysql_db:
    name: mailserver
    collation: utf8_unicode_ci

- name: create sql mysql user
  mysql_user:
    name: mailuser
    password: "{{ lookup('password', '/root/password.mysql chars=ascii_letters,digits,hexdigits length=15') }}"
    priv: 'mailserver.*:SELECT'
    host: localhost

- name: create a table for the domains
  shell: >
    CREATE TABLE `virtual_domains` (`id` int(11) NOT NULL auto_increment, `name` varchar(50) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

- name: create a table for all the email addresses and passwords
  shell: >
    CREATE TABLE `virtual_users` (
      `id` int(11) NOT NULL auto_increment,
      `domain_id` int(11) NOT NULL,
      `password` varchar(106) NOT NULL,
      `email` varchar(100) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `email` (`email`),
      FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

- name: create a table for the email aliases:
  shell: >
    CREATE TABLE `virtual_aliases` (
      `id` int(11) NOT NULL auto_increment,
      `domain_id` int(11) NOT NULL,
      `source` varchar(100) NOT NULL,
      `destination` varchar(100) NOT NULL,
      PRIMARY KEY (`id`),
      FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

####### define root password #######

- name: change mysql root password
  mysql_user:
    state: present
    name: root
    host: localhost
    password: "{{ lookup('password', '/root/password_root.mysql chars=ascii_letters,digits,hexdigits length=15') }}"

- name: insert mysql root user name into root password file
  lineinfile:
    dest: /root/password_root.mysql
    insertbefore: BOF
    line: 'root'
