---
- name: install pma and trivia
  yum:
    name: "{{ pma_packages }}"
    state: latest
    update_cache: yes
    enablerepo: remi-php{{ php_version }}
  vars:
    pma_packages:
    - phpmyadmin
    - python-passlib

- name: create symlink info phpmyadmin folder
  file:
    state: link
    src: /usr/share/phpMyAdmin
    path: /usr/share/phpmyadmin

- name: check if there is apache
  stat:
    path: /usr/sbin/httpd
  register: httpd_status

- name: check if there is php-fpm
  stat:
    path: /usr/sbin/php-fpm
  register: php_fpm_status

- name: copy fpm nginx config
  copy:
    src: pma_centos_fpm.conf
    dest: /etc/php-fpm.d/phpmyadmin.conf
  notify: restart php-fpm centos
  when: php_fpm_status.stat.exists

- name: copy phpmyadmin nginx conf block
  template:
    src: pma_centos_nginx.conf
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  notify: restart nginx
  when: php_fpm_status.stat.exists

- name: copy modphp nginx handler confing
  template:
    src: pma_nginx_modphp.conf
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  when: httpd_status.stat.exists
  notify: restart nginx

- name: add http auth for pma
  htpasswd:
    path: /etc/nginx/conf.d/htpasswd
    name: pma_admin
    password: "{{ lookup('password', '/root/pma_password chars=ascii_letters,digits,hexdigits length=15') }}"
  notify: restart nginx

- name: insert pmd_admin user name into password file
  blockinfile:
    dest: /root/pma_password
    insertbefore: BOF
    block: |

      phpmyadmin
      http://{{ ansible_default_ipv4.address }}/pma/
      Данные для http авторизации:
      Логин: pma_admin
