---
#- name: install pma and trivia
#  apt:
#    name: "{{ pma_packages }}"
#    state: latest
#    update_cache: yes
#    install_recommends: no
#  vars:
#    pma_packages:
#    - phpmyadmin
#    - python-passlib

- name: install python-passlib
  apt:
    name: python-passlib
    state: latest
    update_cache: yes

- name: install phpmyadmin
  shell: |


- name: check if there is apache
  stat:
    path: /etc/apache2/apache2.conf
  register: apache2_status

- name: check if there is php-fpm
  stat:
    path: /usr/sbin/php-fpm{{ php_version_u }}
  register: php_fpm_status

- name: copy fpm pool
  copy:
    src: pma_debian_fpm.conf
    dest: /etc/php/{{ php_version_u }}/fpm/pool.d/phpmyadmin.conf
  when: php_fpm_status.stat.exists
  notify: restart php-fpm debian

- name: copy fpm nginx config
  template:
    src: pma_debian_nginx.conf
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  when: php_fpm_status.stat.exists
  notify: restart nginx

- name: copy modphp nginx handler confing
  template:
    src: pma_nginx_modphp.conf
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  when: apache2_status.stat.exists
  notify: restart nginx

- name: copy apache vhost config
  template:
    src: pma_debian_apache.conf
    dest: /etc/apache2/sites-available/phpmyadmin.conf
  when: apache2_status.stat.exists
  notify: restart apache2

- name: create apache vhost file symlink
  file:
    state: link
    path: /etc/apache2/sites-enabled/phpmyadmin.conf
    src: /etc/apache2/sites-available/phpmyadmin.conf
  when: apache2_status.stat.exists
  notify: restart apache2

- name: add http auth for pma
  htpasswd:
    path: /etc/nginx/conf.d/htpasswd
    name: pma_admin
    password: "{{ lookup('password', '/root/02-pma_password chars=ascii_letters,digits,hexdigits length=15') }}"
  notify: restart nginx

- name: insert pmd_admin user name into password file
  blockinfile:
    marker: ''
    dest: /root/02-pma_password
    insertbefore: BOF
    block: |

      phpmyadmin
      http://{{ ansible_default_ipv4.address }}/pma/
      Данные для http авторизации:
      Логин: pma_admin
