---
- name: install pma and trivia
  apt:
    name: "{{ pma_packages }}"
    state: latest
    update_cache: yes
  vars:
    pma_packages:
    - phpmyadmin
    - python-passlib

- name: check if there is apache
  stat:
    path: /usr/sbin/apache2
  register: apache2_status

- name: check if there is php-fpm
  stat:
    path: /usr/sbin/php-fpm
  register: php_fpm_status

- name: copy phpmyadmin fpm pool
  copy:
    src: pma_centos_fpm.conf
    dest: /etc/php-fpm.d/phpmyadmin.conf
  notify: restart php-fpm debian
  when: php_fpm_status.stat.exists

- name: copy phpmyadmin nginx conf block
  template:
    src: pma_debian_nginx.conf
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  when: php_fpm_status.stat.exists
  notify: reload nginx

- name: copy phpmyadmin nginx php handler conf block
  template:
    src: pma_nginx_modphp.conf
    dest: /etc/nginx/conf.d/phpmyadmin.conf
  when: apache2_status.stat.exists
  notify: reload nginx

- name: copy apache pma vhost config
  template:
    src: pma_debian_apache.conf
    dest: /etc/apache2/sites-available/phpmyadmin.conf
  when: apache2_status.stat.exists
  notify: reload nginx

- name: create vhost file symlink
  file:
    state: link
    path: /etc/apache2/sites-enabled/phpmyadmin.conf
    src: /etc/apache2/sites-available/phpmyadmin.conf

- name: add http auth for pma
  htpasswd:
    path: /etc/nginx/conf.d/htpasswd
    name: pma_admin
    password: "{{ lookup('password', '/root/password.pma chars=ascii_letters,digits,hexdigits length=15') }}"
