---
###################### Debian
- name: install ufw and dependencies Debian/Ubuntu
  apt: name={{ item }} state=latest update_cache=true
  loop:
    - ufw
  when:
      - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: check that ipv6 is enabled in ufw
  lineinfile:
    path: /etc/default/ufw
    regex: '^IPV6='
    line: 'IPV6=yes'

# - name: Enable ssh, http(s) on ufw
# - name: Activate ufw


###################### CentOS

- name: install firewalld and dependencies on CentOS
  yum: name={{ item }} state=latest update_cache=true
  loop:
    - firewalld
  when:
      - ansible_facts['distribution'] == "CentOS"

- name: Make sure firewalld is started and enabled
  service: name="{{ item }}" state=started enabled=yes
  loop:
    - firewalld

- name: Enable http(s) on firewall-cmd
  firewalld: service="{{ item }}" state=enabled permanent=yes zone=public
  loop:
    - http
    - https
