---
- name: add mariadb repo
  yum_repository:
    name: MariaDB
    description: MariaDB 10.3 CentOS
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: install mariadb and trivia
  yum:
    name: "{{ mysql_packages }}"
  vars:
    mysql_packages:
    - mariadb-server
    - MySQL-python

- name: change mysql bind-address
  lineinfile:
    path: /etc/my.cnf.d/server.cnf
    regexp: '^#bind-address'
    line: 'bind-address = 127.0.0.1'

- name: Ensure mysql is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: add website db
  mysql_db:
    state: present
    name: "{{ ansible_hostname }}"
    collation: utf8_unicode_ci
  tag: website_stack

- name: add db user
  mysql_user:
    state: present
    name: "{{ ansible_hostname }}"
    host: localhost
    password: "{{ lookup('password', '/root/password.mysql chars=ascii_letters,digits,hexdigits length=15') }}"
    priv: '{{ ansible_hostname }}.*:ALL'
  tag: website_stack

- name: insert mysql user name into user password file
  lineinfile:
    dest: /root/password.mysql
    insertbefore: BOF
    line: "{{ ansible_hostname }}"
  tag: website_stack

- name: remove anonymous users
  mysql_user:
    state: absent
    name: ''
    host_all: yes

- name: remove test db
  mysql_db:
    state: absent
    name: test

- name: change root password
  mysql_user:
    state: present
    name: root
    host: localhost
    password: "{{ lookup('password', '/root/password_root.mysql chars=ascii_letters,digits,hexdigits length=15') }}"
  tag: website_stack

- name: insert root mysql user name into root password file
  lineinfile:
    dest: /root/password_root.mysql
    insertbefore: BOF
    line: 'root'
  tag: website_stack
