---
- name: add mariadb repo
  yum_repository:
    name: MariaDB
    description: MariaDB 10.3 CentOS
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64

- name: install mariadb and trivia
  yum:
    name: "{{ mysql_packages }}"
  vars:
    mysql_packages:
    - mariadb
    - MySQL-python

- name: change mysql bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127\.0\.0\.1'
    line: 'bind-address = 0.0.0.0'

- name: Ensure mysql is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: add app db
  mysql_db:
    state: present
    name: "{{ ansible_hostname }}"

- name: add db user
  mysql_user:
    state: present
    name: "{{ ansible_hostname }}"
    host: localhost
    password: "{{ ansible_hostname }}"
    priv: '{{ ansible_hostname }}.*:ALL'
