---
- name: Install mysql and tools
  apt:
    state: latest
    update_cache: yes
    name: "{{ mysql_packages }}"
  vars:
      mysql_packages:
      - mysql-server
      - python-mysqldb

- name: change mysql bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127\.0\.0\.1'
    line: 'bind-address = 127.0.0.1'

- name: Ensure mysql is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: add app db
  mysql_db:
    state: present
    name: "{{ ansible_hostname }}"

- name: add db user
  mysql_user:
    state: present
    name: "{{ ansible_hostname }}"
    host: localhost
    password: "{{ ansible_hostname }}"
    priv: '{{ ansible_hostname }}.*:ALL'
