---
- name: Install mysql and tools
  apt:
    state: latest
    update_cache: yes
    name: "{{ mysql_packages }}"
  vars:
      mysql_packages:
      - mysql-server
      - python-mysqldb

- name: change mysql bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127\.0\.0\.1'
    line: 'bind-address = 127.0.0.1'

- name: Ensure mysql is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: add app db
  mysql_db:
    state: present
    name: "{{ ansible_hostname }}"

- name: add db user
  mysql_user:
    state: present
    name: "{{ ansible_hostname }}"
    host: localhost
    password: "{{ lookup('password', '/root/password.mysql chars=ascii_letters,digits,hexdigits length=15') }}"
    priv: '{{ ansible_hostname }}.*:ALL'

- name: insert mysql user name into user password file
  lineinfile:
    dest: /root/password.mysql
    insertbefore: BOF
    line: "{{ ansible_hostname }}"

- name: remove anonymous users
  mysql_user:
    state: absent
    name: ''
    host_all: yes

- name: remove test db
  mysql_db:
    state: absent
    name: test

- name: change root password
  mysql_user:
    state: present
    name: root
    host: localhost
    password: "{{ lookup('password', '/root/password_root.mysql chars=ascii_letters,digits,hexdigits length=15') }}"

# TODO
# delete anon mysql users
# change root
