---
#- name: create site group
#     group:
#    name: {{ ansible_hostname }}

- name: create site user
  user:
    name: "{{ ansible_hostname }}"
    #uid: 48
    #group: apache
    password: "{{ lookup('password', '/root/password.sftp chars=ascii_letters,digits,hexdigits length=15') | password_hash('sha512') }}"
    shell: /sbin/nologin
    home: /var/www/{{ vhost }}/

- name: create user uid
  user:
    name: "{{ ansible_hostname }}"
    uid: 48
    group: apache
    non_unique: yes

#- name: set site dir permissions
#  file:
#    state: directory
#    path: /var/www/{{ vhost }}/
#    chmod: 0775
#    owner: {{ ansible_hostname }}
#    group: {{ ansible_hostname }}

- name:
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    block: |
      Match User {{ ansible_hostname }}
      ForceCommand internal-sftp
      PasswordAuthentication yes
      #ChrootDirectory /var/www/{{ vhost }}/
      PermitTunnel no
      AllowAgentForwarding no
      AllowTcpForwarding no
      X11Forwarding no
  notify: restart sshd
