---
- name: install openssh-server
  yum:
    name: openssh-server
  state: latest
  update_cache: yes

#- name: create site group
#     group:
#    name: {{ ansible_hostname }}

- name: create site user
  user:
    name: {{ ansible_hostname }}
    uid: 48
    gid: 48
    password: "{{ lookup('password', '/root/password.sftp chars=ascii_letters,digits,hexdigits length=15') }}"
    shell: /sbin/nologin

#- name: set site dir permissions
#  file:
#    state: directory
#    path: /var/www/{{ vhost }}/
#    chmod: 0775
#    owner: root
#    group: {{ ansible_hostname }}

- name:
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    block: |
      Match User {{ ansible_hostname }}
      ForceCommand internal-sftp
      PasswordAuthentication yes
      ChrootDirectory /var/www/{{ vhost }}/
      PermitTunnel no
      AllowAgentForwarding no
      AllowTcpForwarding no
      X11Forwarding no
  notify: restart sshd
