---
- name: enable ssh on ufw
  ufw:
    rule: allow
    port: ssh
    proto: tcp

#- name: create site group
#  group:
#    name: {{ ansible_hostname }}

- name: create site user
  user:
    name: "{{ ansible_hostname }}"
    uid: 33
    group: www-data
    non_unique: yes
    password: "{{ lookup('password', '/root/password.sftp chars=ascii_letters,digits,hexdigits length=15') | password_hash('sha512') }}"
    shell: /usr/sbin/nologin
    home: /var/www/{{ vhost }}/

#- name: set site dir permissions
#  file:
#    state: directory
#    path: /var/www/{{ vhost }}/
#    chmod: 0775
#    owner: root
#    group: {{ ansible_hostname }}

- name: add sshd user part
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    block: |
      Match User {{ ansible_hostname }}
      ForceCommand internal-sftp
      PasswordAuthentication yes
      PermitTunnel no
      AllowAgentForwarding no
      AllowTcpForwarding no
      X11Forwarding no
  notify: restart sshd

- name: change ftp-subsystem
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Subsystem'
    line: 'Subsystem       sftp    internal-sftp'
