---
- name: install packages
  yum:
    name: "{{ main_packages }}"
    update_cache: yes
  vars:
    main_packages:
      - postfix

- name: Enable pop and imap on firewall-cmd
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: public
  loop:
    - smtp
    - smtps
    - smtp-submission

#TODO
# generate ssl cert using https://e-rave.nl/create-a-self-signed-ssl-key-for-postfix
