---
- name: install packages
  yum:
    name: "{{ main_packages }}"
    update_cache: yes
  vars:
    main_packages:
      - dovecot
      - dovecot-mysql

#TODO
#add user vmail for dovecot:
#useradd -u 150 vmail -g 12 -s /bin/nologin vmail
