---
- name: install packages
  yum:
    name: "{{ main_packages }}"
    update_cache: yes
  vars:
    main_packages:
      - dovecot
      - dovecot-mysql

#TODO
#1. add user vmail for dovecot: useradd -u 150 vmail -g 12 -s /bin/nologin vmail
#2. mkdir /var/vmail; chown: vmail:mail /var/vmail

- name: Enable pop and imap on firewall-cmd
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: public
  loop:
    - pop3
    - pop3s
    - imap
    - imaps
