---
- name: install memcached
  apt:
    name: "{{ items }}"
    update_cache: yes
  loop:
    - php{{ php_version }}-memcached
    - memcached

- name: check if memcached is started and enabled
  service:
    name: memcached
    state: started
    enabled: yes

- name: additional check
  shell: echo "stats settings" | nc localhost 11211

- name: Start daemon on 127.0.0.1 only
  lineinfile: dest=/etc/sysconfig/memcached regexp='^OPTIONS=' line='OPTIONS="-l 127.0.0.1"' state=present
  notify: restart memcached

- name: Set memcached memory
  lineinfile: dest=/etc/sysconfig/memcached regexp='^CACHESIZE=' line='CACHESIZE="{{ memcached_memory }}"' state=present
  notify: restart memcached
  when: memcached_memory is defined
